scraper_config:
  'num_pages': 20
  'include_retweets': true
  'oldest_date': None
  'checkpoint': None
sentiment_config:
  'model_path': 'resource/models/sentiment/bert_model.ckpt'
lda_config:
  'models_file': models.json
inference_config:
  'specificity': 0.9
  'sensitivity': 0.9