scraper_config:
  'num_pages': 20
  'include_retweets': true
  'oldest_date': None
  'checkpoint': None
sentiment_config:
  'model_path': 'logs/tests/sentiment_bert/version_1/_ckpt_epoch_0_v2.ckpt'
inference_config:
  'specificity': 0.9
  'sensitivity': 0.9