scraper_config:
  'num_pages': 20
  'include_retweets': true
  'oldest_date': None
  'checkpoint': None
sentiment_config:
  'model_path': 'resource/models/sentiment/bert_model.ckpt'
lda_config:
  'model_path': 'resource/models/lda/{}/model'
  'dictionary_path': 'resource/models/lda/{}/dictionary'
  'models_file': 'resource/models/lda/user_models.json'
inference_config:
  'specificity': 0.86
  'sensitivity': 0.86